name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Build Docker Image
        run: |
          docker build -t lyonga/launch/nginxapp:latest 
          
      - name: Push Docker Image to Docker Hub
        run: docker push lyonga/launch/nginxapp:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag and Push Docker Image to Amazon ECR
        run: |
          docker tag nginx:latest ${{ steps.login-ecr.outputs.registry }}/lyonga/launch/nginxapp:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/lyonga/launch/nginxapp:latest
