name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Build and Tag Docker Image
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | awk -F / '{print $NF}')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          IMAGE_TAG="$BRANCH_NAME-$COMMIT_HASH"

          docker build -t lyonga/launch:latest .
          docker tag lyonga/launch:latest lyonga/launch:latest
          
      - name: Push Docker Image to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: lyonga/launch:latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag and Push Docker Image to Amazon ECR
        run: |
          docker tag lyonga/launch:latest ${{ steps.login-ecr.outputs.registry }}/lyonga/launch:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/lyonga/launch:latest
