name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Build Docker Image
      uses: docker/build-push-action@v2  
      with:
        context: .
        push: true
        tags: GA/image:${{ env.GITHUB_SHA }}
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Push Docker Image
      uses: docker/push-action@v2
      with:
        tags: GA:${{ env.GITHUB_SHA }}
        repository: demo-repo
