name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Build Docker Image
      uses: docker/build-push-action@v2  
      with:
        context: .
        push: true
        tags: test-demo/image:${{ env.GITHUB_SHA }}
        
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
    - name: Push Docker Image
      uses: lyonga/test-demo/push-action@v2
      with:
        tags: test-demo:${{ env.GITHUB_SHA }}
